CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
);
CREATE TABLE contact  (
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
	phone_number int(50) NOT NULL,
    subject VARCHAR(100) NOT NULL,
	comment VARCHAR(100) NOT NULL,
);
